
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by Apache CXF 2.0.8
 * Tue Feb 10 13:38:29 BRST 2009
 * Generated source version: 2.0.8
 * 
 */

@WebServiceClient(name = "MU_WEBSERVICE", 
                  wsdlLocation = "http://192.168.100.191/mu_integracao/MU_WEBSERVICE.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class ErpService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://tempuri.org/", "MU_WEBSERVICE");
    public final static QName ServiceSoap12 = new QName("http://tempuri.org/", "MU_WEBSERVICESoap12");
    public final static QName ServiceSoap = new QName("http://tempuri.org/", "MU_WEBSERVICESoap");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.100.23/mu_webservice.asmx?WSDL");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://192.168.100.23/mu_webservice.asmx?WSDL");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ErpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ErpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ErpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns Service1Soap12
     */
    @WebEndpoint(name = "Service1Soap12")
    public ErpServiceSoap getErpServiceSoap12() {
        return super.getPort(ServiceSoap12, ErpServiceSoap.class);
    }
    /**
     * 
     * @return
     *     returns Service1Soap
     */
    @WebEndpoint(name = "Service1Soap")
    public ErpServiceSoap getErpServiceSoap() {
        return super.getPort(ServiceSoap, ErpServiceSoap.class);
    }

}
