
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.8
 * Tue Feb 10 13:38:29 BRST 2009
 * Generated source version: 2.0.8
 * 
 */

@WebService(targetNamespace = "http://tempuri.org/", name = "Service1Soap")

public interface ErpServiceSoap {

    @WebResult(name = "IsAtivoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsAtivo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsAtivo")
    @ResponseWrapper(localName = "IsAtivoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsAtivoResponse")
    @WebMethod(operationName = "IsAtivo", action = "http://tempuri.org/IsAtivo")
    public boolean isAtivo();

    @WebResult(name = "BuscaEstoqueResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BuscaEstoque", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscaEstoque")
    @ResponseWrapper(localName = "BuscaEstoqueResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscaEstoqueResponse")
    @WebMethod(operationName = "BuscaEstoque", action = "http://tempuri.org/BuscaEstoque")
    public org.tempuri.ConsultaEstoque buscaEstoque(
        @WebParam(name = "Filial", targetNamespace = "http://tempuri.org/")
        java.lang.String filial
    );
}
